site_name: Star Log-extended eMulator
theme:
    name: material

    # headers for navigating tabs
    features:
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - toc.integrate
    - content.action.edit
    
    palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - footnotes
  - md_in_html

extra_javascript:
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

# allows for API style docs
plugins:
- search:
- mkdocs-jupyter:
# - mkdocstrings:
#     default_handler: python
#     handlers:
#       python:
#         setup_commands:
#           - import sys
#           - sys.path.append("samba")
#         rendering:
#           show_source: true
# watch:
# - samba

nav:
  - index.md
  # - Documentation:
    # - models.md
    # - mixing.md
    # - discrepancy.md
    # - gaussianprocess.md
    # - fprdat.md
    # - priors.md
  # - Tutorials:
  #   - Tutorials/LMM.ipynb
  #   - Tutorials/Bivariate_BMM.ipynb
  #   - Tutorials/GP_BMM.ipynb

repo_url: https://github.com/asemposki/SLM

repo_name: asemposki/SLM

edit_uri: edit/main/docs

copyright: Copyright &copy; 2024 Sudhanva Lalit, Alexandra C. Semposki, and Joshua M. Maldonado. All rights reserved.
