name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed # Trigger when the PR is closed (includes merged state)
permissions:
  contents: write

jobs:
  deploy:
    # Only run this job if the pull request was merged
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: pip install mkdocstrings-python
      - run: pip install mkdocs-jupyter
      - run: pip install -r requirements.txt
      - run: pip install -e .
      - run: mkdocs gh-deploy --force
