# New update to the ci file.
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main # This will trigger for PR events, but the 'deploy' job's if condition will filter it.

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    # This condition correctly captures pushes to main (including merges)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    # The previous condition was also fine:
    # if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    # But relying solely on 'push' to main is simpler for deployment.

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: "pip"

      - name: Cache MkDocs build artifacts
        id: cache-mkdocs-material
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ hashFiles('requirements.txt') }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Build and deploy MkDocs
        run: mkdocs gh-deploy --force --clean
