# .github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Grant necessary permissions for the GITHUB_TOKEN
permissions:
  contents: write # Allows checking out code and installing dependencies
  pages: write    # Allows managing GitHub Pages deployments
  id-token: write # Required for OIDC authentication for pages deployment

jobs:
  # This job builds your documentation
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: "pip"

      - name: Cache MkDocs build artifacts
        id: cache-mkdocs-material
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ hashFiles('requirements.txt') }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Build MkDocs documentation
        run: mkdocs build --clean # Just build, don't deploy here

      # Upload the 'site' directory as an artifact for the deployment job
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # Use v3
        with:
          path: ./site # The directory where MkDocs builds the static files

  # This job deploys the artifact to GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # This job depends on the 'build' job completing successfully
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Only deploy on push to main
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Use v4
